name: output the github context information
on:
  - push
  - workflow_dispatch
jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - name: log the github context
        run: echo "${{ toJson(github) }}"