name: run-unit-test
on: 
  push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      
      - name: install node js@18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: install dependencies
        run: npm ci
      
      - name: run unit test
        run: npm run test