name: run-unit-test
on: 
  - push
  - workflow_dispatch
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      
      - name: install node js@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: install dependencies
        run: npm ci
      
      - name: run unit test
        run: npm run test
  build:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      
      - name: install node js@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: install dependencies
        run: npm ci
      
      - name: build
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      
      - name: install node js@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: install dependencies
        run: npm ci

      - name: upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            dist
            package.json
          
      - name: deploy
        run: echo "deploying the code"